esphome:
    name: tablelighting2000
    includes:
      - components/ble_scanner/bleScanner.h
    libraries:
      - ArduinoJSON

esp32:
    board: nodemcu-32s

custom_component:
  - lambda: |-
      auto ble = new jcc::bleScanner();
      return {ble};

    components: 
      - id: ble

# Ble tracker
esp32_ble_tracker:

text_sensor:
  - platform: ble_scanner
    name: "BLE Devices Scanner"
    on_value:
      lambda: |-
        static_cast<jcc::bleScanner*>(id(ble))->processDevice(x);
        


#Wireless config system
#Set up AP for management (only available to us)
#wifi: 
#    ap: #Access point
 #       ssid: SagraMezzano_1
 #       password: suinoaureo

 #   output_power: "8.5dB" #save some power

logger: #Log to serial

#web_server: #HTML control page
#    port: 80
#    local: true

#External inputs
binary_sensor:
     #External on-off key. Has right of way over BLE
     - platform: gpio
       id: external_light_switch
       pin: 
         number: GPIO26
         inverted: true
       on_press: 
         then:
           - light.toggle: main_light

     - platform: template
       name: "nearby devices"
       lambda: |-
        jcc::bleScanner* scanner{static_cast<jcc::bleScanner*>(id(ble))};
        return scanner->checkNearbyDevices(-60);

#Light components
#Circular light of the table
light:
    - platform: rgb
      id: main_light
      name: "Striscia RGB"
      red: circle_red
      green: circle_green
      blue: circle_blue

#Output
output:
    #PWM outputs
    - platform: ledc
      id: circle_red
      pin: GPIO32
    - platform: ledc
      id: circle_green
      pin: GPIO33
    - platform: ledc
      id: circle_blue
      pin: GPIO25

# Other lights shall be defined here