esphome:
    name: tablelighting2000
    includes:
      - components/ble_scanner/bleScanner.h

esp32:
    board: nodemcu-32s

custom_component:
  - lambda: |-
      auto ble = new jcc::bleScanner();
      return {ble};

    components: 
      - id: ble

# Ble tracker
esp32_ble_tracker:

# All the non binary sensors
sensor:
  - platform: ble_rssi
  # Detect all BLe devices with the 0x1800 service (i.e the generic access. every commercia ble device has this)
  # if it does not work, try with 0x180f (battery service)
    service_uuid: "180A" 
    #mac_address: 56:9a:e7:66:d8:be
    id: rssi_sensor
    name: "HumanDetector"

    #on_value: #when receiving an rssi value
      #then:

text_sensor:
  - platform: ble_scanner
    name: "BLE Devices Scanner"
    on_value:
      lambda: |-
        static_cast<jcc::bleScanner*>(id(ble))->processDevice(x);
        


#Wireless config system
#Set up AP for management (only available to us)
wifi: 
    ap: #Access point
        ssid: SagraMezzano_1
        password: suinoaureo

    output_power: "8.5dB" #save some power

logger: #Log to serial

web_server: #HTML control page
    port: 80
    local: true

#External inputs
binary_sensor:
     #External on-off key. Has right of way over BLE
     - platform: gpio
       id: external_light_switch
       pin: 
         number: GPIO26
         inverted: true
       on_press: 
         then:
           - light.toggle: main_light

#Light components
#Circular light of the table
light:
    - platform: rgb
      id: main_light
      name: "Striscia RGB"
      red: circle_red
      green: circle_green
      blue: circle_blue

#Output
output:
    #PWM outputs
    - platform: ledc
      id: circle_red
      pin: GPIO32
    - platform: ledc
      id: circle_green
      pin: GPIO33
    - platform: ledc
      id: circle_blue
      pin: GPIO25

# Other lights shall be defined here